In [1]:
from xml.dom import minidom
import nltk
import glob

In [2]:
import os
os.chdir("C:\\Users\\Admin\\Documents\\NLP Project\\INLI@FIRE2017")
os.getcwd()

'C:\\Users\\Admin\\Documents\\NLP Project\\INLI@FIRE2017'

In [3]:
#Test_file = open('INLI_Train_Bengali_1','r')
bengali = []
hindi = []
kannada = []
malayalam = []
tamil = []
telugu = []
for name in glob.glob("*.xml"):
    #print (name)
    if "BEN" in name[11:]:
        bengali.append(name)
    elif "HIN" in name[11:]:
        hindi.append(name)
    elif "KAN" in name[11:]:
        kannada.append(name)
    elif "MAL" in name[11:]:
        malayalam.append(name)
    elif "TAM" in name[11:]:
        tamil.append(name)
    elif "TEL" in name[11:]:
        telugu.append(name)

In [4]:
print (len(hindi),len(bengali),len(malayalam),len(kannada),len(tamil),len(telugu))
hindi_dataset = []
bengali_dataset = []
malay_dataset = []
kannada_dataset = []
tamil_dataset = []
telugu_dataset = []
grand_list = []

211 202 200 203 207 210


In [5]:
print ("Total = " + str(len(hindi)+len(bengali)+len(malayalam)+len(kannada)+len(tamil)+len(telugu)))

Total = 1233


In [6]:
for f in hindi:
    f = open(f,encoding="utf8")
    doc = minidom.parse(f)
    hindi_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('hindi',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [7]:
for f in tamil:
    f = open(f,encoding="utf8")
    doc = minidom.parse(f)
    tamil_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('tamil',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [8]:
for f in bengali:
    f = open(f,encoding="utf8")
    doc = minidom.parse(f)
    bengali_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('bengali',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [9]:
for f in telugu:
    f = open(f,encoding="utf8")
    doc = minidom.parse(f)
    telugu_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('telugu',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [10]:
for f in kannada:
    f = open(f,encoding="utf8")
    doc = minidom.parse(f)
    kannada_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('kannada',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [11]:
for f in malayalam:
    f = open(f,encoding="utf8")
    doc = minidom.parse(f)
    malay_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('malayalam',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [12]:
print(len(grand_list))

1233


In [52]:
grand_list

[('hindi',
  'It is not pakistan problem, in India 99%Muslims support pakistan, 1st we have to send this people to Pakistan than only peaceful India will happening.\nBest Gift on the eve on my birthday...waiting eagerly\nIn India so many commedian are there,next person should get chance and continue the show.\n122 crore 1 day record bahubali, bahubali awesome movie.\nengineering and joined this business so dont\nIf any world leader wish to mediate vid talks between India n Pakistan, dey first stop d terrorism fm Pakistan! Let dem do first as Indians can handle any dam thing!\nZ news media excellent top in india\nGov make a law son of every politician must service in army and posted on boaders..\n'),
 ('hindi',
  'why posting about Porkistan , terrorist nation Porkistan should end the attack on minority Hindus and Sikhs and should end cross border terrorism , even they killed a good student like Mashal Khan..who had bit of respect for Hindus\nThanks Ganvirji for your patriotic job conti

In [13]:
from sklearn import svm
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [14]:
def create_tfidf_training_data(docs):
    y = [d[0] for d in docs]

    # Create the document corpus list
    corpus = [d[1] for d in docs]

    # Create the TF-IDF vectoriser and transform the corpus
    vectorizer = TfidfVectorizer(min_df=1)
    X = vectorizer.fit_transform(corpus)
    return X, y

In [20]:
X, y = create_tfidf_training_data(grand_list)

In [21]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.2, random_state=42
)

In [49]:
clf = svm.SVC(C=1000000.0, kernel='rbf', gamma= 0.1)     # C = 100000.0, kernel = 'rbf'
clf.fit(X_train, y_train)

SVC(C=1000000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [50]:
from sklearn.metrics import confusion_matrix
pred = clf.predict(X_test)

In [51]:
print(clf.score(X_test, y_test))
print(confusion_matrix(pred, y_test, labels=["hindi", "tamil", "bengali", "telugu", "kannada", "malayalam"]))

0.846153846154
[[37  0  3  0  1  1]
 [ 0 41  1  0  0  1]
 [ 4  1 35  0  2  0]
 [ 0  3  0 36  1  2]
 [ 1  2  0  2 31  2]
 [ 0  2  2  1  6 29]]
