In [1]:
from xml.dom import minidom
import nltk
import glob

In [2]:
import os
os.chdir("C:\\Users\\Admin\\Documents\\NLP Project\\INLI@FIRE2017")
os.getcwd()

'C:\\Users\\Admin\\Documents\\NLP Project\\INLI@FIRE2017'

In [3]:
#Test_file = open('INLI_Train_Bengali_1','r')
bengali = []
hindi = []
kannada = []
malayalam = []
tamil = []
telugu = []
for name in glob.glob("*.xml"):
    #print (name)
    if "BEN" in name[11:]:
        bengali.append(name)
    elif "HIN" in name[11:]:
        hindi.append(name)
    elif "KAN" in name[11:]:
        kannada.append(name)
    elif "MAL" in name[11:]:
        malayalam.append(name)
    elif "TAM" in name[11:]:
        tamil.append(name)
    elif "TEL" in name[11:]:
        telugu.append(name)

In [4]:
print (len(hindi),len(bengali),len(malayalam),len(kannada),len(tamil),len(telugu))
hindi_dataset = []
bengali_dataset = []
malay_dataset = []
kannada_dataset = []
tamil_dataset = []
telugu_dataset = []
grand_list = []

211 202 200 203 207 210


In [5]:
print ("Total = " + str(len(hindi)+len(bengali)+len(malayalam)+len(kannada)+len(tamil)+len(telugu)))

Total = 1233


In [6]:
for f in hindi:
    f = open(f,'r')
    doc = minidom.parse(f)
    hindi_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('hindi',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [7]:
for f in tamil:
    f = open(f,'r')
    doc = minidom.parse(f)
    tamil_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('tamil',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [8]:
for f in bengali:
    f = open(f,'r')
    try:
        doc = minidom.parse(f)
        bengali_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
        grand_list.append(('bengali',doc.documentElement.childNodes[5].firstChild.nodeValue))
    except:
        True

In [9]:
for f in telugu:
    f = open(f,'r')
    doc = minidom.parse(f)
    telugu_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('telugu',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [10]:
for f in kannada:
    f = open(f,'r')
    doc = minidom.parse(f)
    kannada_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
    grand_list.append(('kannada',doc.documentElement.childNodes[5].firstChild.nodeValue))

In [11]:
for f in malayalam:
    f = open(f,'r')
    try:
        doc = minidom.parse(f)
        malay_dataset.append(doc.documentElement.childNodes[5].firstChild.nodeValue)
        grand_list.append(('malayalam',doc.documentElement.childNodes[5].firstChild.nodeValue))
    except:
        True

In [12]:
print( len(tamil_dataset), len(hindi_dataset), len(bengali_dataset), len(kannada_dataset), len(telugu_dataset), len(malay_dataset))
print ("Total = " + str(len(tamil_dataset) + len(hindi_dataset) + len(bengali_dataset) + len(kannada_dataset) + len(telugu_dataset) + len(malay_dataset)))

207 211 201 203 210 196
Total = 1228


In [13]:
import re, string
exclude = set(string.punctuation)

In [14]:
tam = []
for line in tamil_dataset:
    line = line.lower()
    line = re.sub(r"\d", "", line)
    l=''
    for ch in line :
        if ch in exclude :
            l+=' '
        else:
            l+=ch
    tam.append(l)

In [15]:
hin = []
for line in hindi_dataset:
    line = line.lower()
    line = re.sub(r"\d", "", line)
    l=''
    for ch in line :
        if ch in exclude :
            l+=' '
        else:
            l+=ch
    hin.append(l)

In [16]:
ben = []
for line in bengali_dataset:
    line = line.lower()
    line = re.sub(r"\d", "", line)
    l=''
    for ch in line :
        if ch in exclude :
            l+=' '
        else:
            l+=ch
    ben.append(l)

In [17]:
kan = []
for line in kannada_dataset:
    line = line.lower()
    line = re.sub(r"\d", "", line)
    l=''
    for ch in line :
        if ch in exclude :
            l+=' '
        else:
            l+=ch
    kan.append(l)

In [18]:
mal = []
for line in malay_dataset:
    line = line.lower()
    line = re.sub(r"\d", "", line)
    l=''
    for ch in line :
        if ch in exclude :
            l+=' '
        else:
            l+=ch
    mal.append(l)

In [19]:
tel = []
for line in telugu_dataset:
    line = line.lower()
    line = re.sub(r"\d", "", line)
    l=''
    for ch in line :
        if ch in exclude :
            l+=' '
        else:
            l+=ch
    tel.append(l)

In [20]:
print( len(tam), len(hin), len(ben), len(kan), len(tel), len(mal))

207 211 201 203 210 196


# Applying bigrams classifier

In [21]:
from nltk import ngrams
n = 2

In [22]:
ngram_list = []
tam_grams = []
hin_grams = []
ben_grams = []
tel_grams = []
kan_grams = []
mal_grams = []

In [23]:
for sentence in tam:
    sixgrams = ngrams(sentence.split(),n)
    for grams in sixgrams:
        temp = ""
        for g in grams:
            temp = temp + g + " "
        temp = temp[:len(temp)-1]
        ngram_list.append(('tamil',temp))
        tam_grams.append(temp)
print(len(ngram_list))

32916


In [24]:
for sentence in hin:
    sixgrams = ngrams(sentence.split(),n)
    for grams in sixgrams:
        temp = ""
        for g in grams:
            temp = temp + g + " "
        temp = temp[:len(temp)-1]
        ngram_list.append(('hindi',temp))
        hin_grams.append(temp)
print(len(ngram_list))

60814


In [25]:
for sentence in ben:
    sixgrams = ngrams(sentence.split(),n)
    for grams in sixgrams:
        temp = ""
        for g in grams:
            temp = temp + g + " "
        temp = temp[:len(temp)-1]
        ngram_list.append(('bengali',temp))
        ben_grams.append(temp)
print(len(ngram_list))

97942


In [26]:
for sentence in kan:
    sixgrams = ngrams(sentence.split(),n)
    for grams in sixgrams:
        temp = ""
        for g in grams:
            temp = temp + g + " "
        temp = temp[:len(temp)-1]
        ngram_list.append(('kannada',temp))
        kan_grams.append(temp)
print(len(ngram_list))

141468


In [27]:
for sentence in tel:
    sixgrams = ngrams(sentence.split(),n)
    for grams in sixgrams:
        temp = ""
        for g in grams:
            temp = temp + g + " "
        temp = temp[:len(temp)-1]
        ngram_list.append(('telugu',temp))
        tel_grams.append(temp)
print(len(ngram_list))

187741


In [28]:
for sentence in mal:
    sixgrams = ngrams(sentence.split(),n)
    for grams in sixgrams:
        temp = ""
        for g in grams:
            temp = temp + g + " "
        temp = temp[:len(temp)-1]
        ngram_list.append(('malayalam',temp))
        mal_grams.append(temp)
print(len(ngram_list))

233043


In [29]:
len(ngram_list)

233043

In [30]:
import time
import numpy as np
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

In [31]:
from sklearn import svm
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [32]:
def create_tfidf_training_data(docs):
    y = [d[0] for d in docs]

    # Create the document corpus list
    corpus = [d[1] for d in docs]

    # Create the TF-IDF vectoriser and transform the corpus
    vectorizer = TfidfVectorizer(min_df=1)
    X = vectorizer.fit_transform(corpus)
    return X, y

In [39]:
X, y = create_tfidf_training_data(ngram_list)

In [40]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.2, random_state=42
)

In [41]:
n_estimators = 10
start = time.time()
clf = OneVsRestClassifier(BaggingClassifier(SVC(kernel='linear', probability=True, class_weight='auto'), max_samples=1.0 / n_estimators, n_estimators=n_estimators), n_jobs = -1)
clf.fit(X_train, y_train)
end = time.time()

In [37]:
from sklearn.metrics import confusion_matrix
pred = clf.predict(X_test)

In [38]:
print(clf.score(X_test, y_test))

0.309940140316


In [58]:
print(confusion_matrix(pred, y_test, labels=["hindi", "tamil", "bengali", "telugu", "kannada", "malayalam"]))

[[ 697  234  362  208  280  237]
 [  81  354  121  158  178  177]
 [ 325  270  803  321  330  316]
 [1335 1914 1735 3615 2387 2371]
 [ 899  937  947 1236 1761 1176]
 [2175 2801 3409 3771 3722 4966]]


In [ ]:
clf = svm.SVC(C=1000000.0, kernel='rbf')
clf.fit(X_train, y_train)

In [ ]:
print(clf.score(X_test, y_test))

In [ ]:
print(confusion_matrix(pred, y_test, labels=["hindi", "tamil", "bengali", "telugu", "kannada", "malayalam"]))